import { useEffect, useMemo, useState } from 'react'
import './App.css'
import './board-fix.css'
type Side='sente'|'gote'; type Kind='lion'|'giraffe'|'elephant'|'chick'|'hen'; type RuleMode='normal'|'beginner'; type PieceSet='wagashi'|'western'|'mix'; type VisualTheme='sweets'; export type AppVariant='okashi'|'samurai'; type Piece={side:Side;kind:Kind}; type Move={from?:number;hand?:Kind;to:number;piece:Kind;side:Side;captured?:Kind;promote?:boolean}; type Position={board:(Piece|null)[];hands:Record<Side,Kind[]>;turn:Side;winner?:Side;reason?:string}
const F=['1','2','3'],R=['一','二','三','四']; const L:Record<PieceSet,Record<Kind,string>>={wagashi:{lion:'あんみつ',giraffe:'だんご',elephant:'さくらもち',chick:'こんぺいとう',hen:'花こんぺいとう'},western:{lion:'ケーキ',giraffe:'エクレア',elephant:'マカロン',chick:'ジェリー',hen:'キャンディ'},mix:{lion:'パフェ',giraffe:'プリン',elephant:'いちご大福',chick:'クッキー',hen:'王冠クッキー'}},V:Record<Kind,number>={lion:1000,giraffe:5,elephant:5,chick:2,hen:7}
const VISUAL_THEMES:Record<VisualTheme,{label:string;pieceRoot:string}>={sweets:{label:'おかし',pieceRoot:'./pieces/sweets'}}
const SAMURAI_NAMES:Record<Kind,string>={lion:'大将',giraffe:'槍武者',elephant:'弓武者',chick:'足軽',hen:'若武者'}
const INITIAL:Position={board:[{side:'gote',kind:'giraffe'},{side:'gote',kind:'lion'},{side:'gote',kind:'elephant'},null,{side:'gote',kind:'chick'},null,null,{side:'sente',kind:'chick'},null,{side:'sente',kind:'elephant'},{side:'sente',kind:'lion'},{side:'sente',kind:'giraffe'}],hands:{sente:[],gote:[]},turn:'sente'}
const other=(s:Side):Side=>s==='sente'?'gote':'sente', clone=(p:Position):Position=>({...p,board:p.board.map(x=>x&&{...x}),hands:{sente:[...p.hands.sente],gote:[...p.hands.gote]}})
function vec(k:Kind,s:Side){const f=s==='sente'?-1:1;if(k==='lion')return[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];if(k==='giraffe')return[[-1,0],[0,-1],[0,1],[1,0]];if(k==='elephant')return[[-1,-1],[-1,1],[1,-1],[1,1]];if(k==='chick')return[[f,0]];return[[f,-1],[f,0],[f,1],[0,-1],[0,1],[-f,0]]}
function pseudo(p:Position,side=p.turn){const a:Move[]=[];p.board.forEach((x,from)=>{if(!x||x.side!==side)return;const r=Math.floor(from/3),c=from%3;vec(x.kind,side).forEach(([dr,dc])=>{const nr=r+dr,nc=c+dc;if(nr<0||nr>3||nc<0||nc>2)return;const to=nr*3+nc,t=p.board[to];if(t?.side!==side)a.push({from,to,piece:x.kind,side,captured:t?.kind,promote:x.kind==='chick'&&(nr===0||nr===3)})})});p.hands[side].forEach(k=>p.board.forEach((x,to)=>{const row=Math.floor(to/3);if(!x&&!(k==='chick'&&(row===0||row===3)))a.push({hand:k,to,piece:k,side})}));return a}
function attacked(p:Position,sq:number,by:Side){return pseudo({...p,hands:{sente:[],gote:[]}},by).some(m=>m.to===sq)}
function apply(p:Position,m:Move,win=true){const n=clone(p),target=n.board[m.to];if(m.from!==undefined)n.board[m.from]=null;else{const i=n.hands[m.side].indexOf(m.piece);n.hands[m.side].splice(i,1)}n.board[m.to]={side:m.side,kind:m.promote?'hen':m.piece};if(target&&target.kind!=='lion')n.hands[m.side].push(target.kind==='hen'?'chick':target.kind);n.turn=other(m.side);if(win){if(target?.kind==='lion'){n.winner=m.side;n.reason='ライオンをつかまえました'}else if(m.piece==='lion'){const goal=m.side==='sente'?0:3;if(Math.floor(m.to/3)===goal&&!attacked(n,m.to,other(m.side))){n.winner=m.side;n.reason='トライに成功しました'}}if(!n.winner&&legal(n).length===0){n.winner=m.side;n.reason='相手に指せる手がありません（詰み）'}}return n}
function legal(p:Position){return pseudo(p).filter(m=>{const n=apply(p,m,false),li=n.board.findIndex(x=>x?.side===p.turn&&x.kind==='lion');return li<0||!attacked(n,li,other(p.turn))})}
function score(p:Position,s:Side){if(p.winner)return p.winner===s?99999:-99999;let v=0;p.board.forEach(x=>{if(x)v+=(x.side===s?1:-1)*V[x.kind]});(['sente','gote']as Side[]).forEach(o=>p.hands[o].forEach(k=>v+=(o===s?1:-1)*V[k]*.9));return v}
function ai(p:Position,lv:number){const root=p.turn,ms=legal(p);if(lv===1)return ms[Math.floor(Math.random()*ms.length)];const depth=lv===2?2:lv===3?4:5;function go(q:Position,d:number,a:number,b:number):number{if(!d||q.winner)return score(q,root);const xs=legal(q);if(!xs.length)return q.turn===root?-90000:90000;if(q.turn===root){let v=-Infinity;for(const m of xs){v=Math.max(v,go(apply(q,m),d-1,a,b));a=Math.max(a,v);if(b<=a)break}return v}let v=Infinity;for(const m of xs){v=Math.min(v,go(apply(q,m),d-1,a,b));b=Math.min(b,v);if(b<=a)break}return v}return ms.map(m=>({m,v:go(apply(p,m),depth-1,-Infinity,Infinity)+Math.random()*.05})).sort((a,b)=>b.v-a.v)[0]?.m}
const note=(m:Move,names:Record<Kind,string>)=>`${m.side==='sente'?'▲':'△'}${F[m.to%3]}${R[Math.floor(m.to/3)]} ${names[m.piece]}${m.hand?'打':''}${m.promote?'成':''}`
function App({variant='okashi'}:{variant?:AppVariant}){const[hist,setHist]=useState<Position[]>([clone(INITIAL)]),[moves,setMoves]=useState<Move[]>([]),[cur,setCur]=useState(0),[sel,setSel]=useState<{from?:number;hand?:number}|null>(null),[players,setPlayers]=useState<Record<Side,'human'|'ai'>>({sente:'human',gote:'ai'}),[level,setLevel]=useState(2),[ruleMode,setRuleMode]=useState<RuleMode>('normal'),[visualTheme,setVisualTheme]=useState<VisualTheme>('sweets'),[pieceSet,setPieceSet]=useState<PieceSet>('mix'),[thinking,setThinking]=useState(false);const p=hist[cur],isSamurai=variant==='samurai',names=isSamurai?SAMURAI_NAMES:L[pieceSet],pieceRoot=isSamurai?'../pieces/samurai':'../pieces/sweets',lm=useMemo(()=>legal(p),[p]),pm=useMemo(()=>pseudo(p),[p]);const isSelected=(m:Move)=>!!sel&&(sel.from!==undefined?m.from===sel.from:m.hand===p.hands[p.turn][sel.hand!]);const sameMove=(a:Move,b:Move)=>a.to===b.to&&a.from===b.from&&a.hand===b.hand;function commit(m:Move,foul=false){const next=apply(p,m,!foul);if(foul){next.winner=other(m.side);next.reason='反則負け：合法手ではない手を指しました'}setHist([...hist.slice(0,cur+1),next]);setMoves([...moves.slice(0,cur),m]);setCur(cur+1);setSel(null)}useEffect(()=>{if(p.winner||players[p.turn]!=='ai'){setThinking(false);return}setThinking(true);const t=setTimeout(()=>{const m=ai(p,level);if(m)commit(m)},350);return()=>clearTimeout(t)},[cur,players,p.turn,p.winner,level]);function tap(i:number){if(thinking||p.winner||players[p.turn]==='ai')return;if(sel){const legalMove=lm.find(m=>m.to===i&&isSelected(m));if(legalMove){commit(legalMove);return}const illegalMove=pm.find(m=>m.to===i&&isSelected(m));if(illegalMove&&ruleMode==='normal'){commit(illegalMove,true);return}}const x=p.board[i];setSel(x?.side===p.turn?{from:i}:null)}function reset(){setHist([clone(INITIAL)]);setMoves([]);setCur(0);setSel(null)}const selectedPseudo=sel?pm.filter(isSelected):[],targets=new Set(selectedPseudo.filter(m=>lm.some(x=>sameMove(x,m))).map(m=>m.to)),illegalTargets=new Set(selectedPseudo.filter(m=>!lm.some(x=>sameMove(x,m))).map(m=>m.to))
return <main className={`app-shell ${isSamurai?'samurai':`sweets-${pieceSet}`}`}><header><div className="brand"><span>{isSamurai?'さ':'お'}</span><div><h1>{isSamurai?'さむらいしょうぎ':'おかししょうぎ'}</h1></div></div><button className="new" onClick={reset}>新しい対局</button></header><section className="game-card">
{(['gote']as Side[]).map(s=><Player key={s} side={s} p={p} thinking={thinking} players={players} setPlayers={setPlayers}/>)}<Hand side="gote" p={p} sel={sel} setSel={setSel} players={players} pieceSet={pieceSet} names={names} pieceRoot={pieceRoot}/><div className="board">{p.board.map((x,i)=><button key={i} onClick={()=>tap(i)} className={`square ${(Math.floor(i/3)+i%3)%2?'shade':''} ${sel?.from===i?'chosen':''} ${targets.has(i)?'target':''} ${ruleMode==='beginner'&&illegalTargets.has(i)?'illegal-target':''}`} aria-label={`${F[i%3]}${R[Math.floor(i/3)]}${x?names[x.kind]:'空き'}${ruleMode==='beginner'&&illegalTargets.has(i)?'、合法手ではありません':''}`}>{x&&<><MovementGuides kind={x.kind} side={x.side}/><div className={`piece ${x.side}`}><PieceIcon kind={x.kind} pieceSet={pieceSet} pieceRoot={pieceRoot}/></div></>}</button>)}</div><Hand side="sente" p={p} sel={sel} setSel={setSel} players={players} pieceSet={pieceSet} names={names} pieceRoot={pieceRoot}/>{(['sente']as Side[]).map(s=><Player key={s} side={s} p={p} thinking={thinking} players={players} setPlayers={setPlayers}/>)}{p.winner&&<div className="result"><span>{p.reason?.startsWith('反則負け')?'❌':'🎉'}</span><div><b>{p.winner==='sente'?'せんて':'ごて'}の勝ち！</b><small>{p.reason}</small></div><button onClick={reset}>もう一局</button></div>}</section>
<section className="controls"><div className="timeline"><button onClick={()=>setCur(0)} disabled={!cur}>|◀</button><button onClick={()=>setCur(cur-1)} disabled={!cur}>◀ 待った</button><div><b>{cur}</b> / {moves.length} 手</div><button onClick={()=>setCur(cur+1)} disabled={cur>=hist.length-1}>進む ▶</button><button onClick={()=>setCur(hist.length-1)} disabled={cur>=hist.length-1}>▶|</button></div><div className="setting"><div><b>対局モード</b><span>{ruleMode==='normal'?'不正手は反則負けになります':'不正な移動先を❌で案内します'}</span></div><select value={ruleMode} onChange={e=>{setRuleMode(e.target.value as RuleMode);setSel(null)}}><option value="normal">通常</option><option value="beginner">入門</option></select></div><div className="setting"><div><b>AIのつよさ</b><span>端末の中だけで考えます</span></div><select value={level} onChange={e=>setLevel(+e.target.value)}><option value="1">やさしい</option><option value="2">ふつう</option><option value="3">つよい</option><option value="4">とてもつよい</option></select></div>{!isSamurai&&<><div className="setting"><div><b>見た目のテーマ</b><span>新しいテーマを追加できます</span></div><select value={visualTheme} onChange={e=>setVisualTheme(e.target.value as VisualTheme)}>{Object.entries(VISUAL_THEMES).map(([id,v])=><option key={id} value={id}>{v.label}</option>)}</select></div><div className="setting"><div><b>おかしの種類</b><span>対局中も変更できます</span></div><select value={pieceSet} onChange={e=>setPieceSet(e.target.value as PieceSet)}><option value="wagashi">和菓子</option><option value="western">洋菓子</option><option value="mix">和洋MIX</option></select></div></>}{isSamurai?<div className="battlefield-setting"><div><b>舞台</b><span>草原と土の戦場</span></div><strong>戦場</strong></div>:<div className="board-setting"><div><b>盤のデザイン</b><span>対局中も変更できます</span></div><BoardStylePicker/></div>}<details><summary>棋譜を見る <span>{moves.length}手</span></summary><ol>{moves.map((m,i)=><li className={cur===i+1?'current':''} key={i}><button onClick={()=>setCur(i+1)}>{note(m,names)}</button></li>)}</ol></details></section><footer>対局はこの端末だけで進みます · オフラインでも遊べます</footer></main>}
function BoardStylePicker(){return <fieldset className="board-styles"><legend>盤のデザイン</legend><label><input id="board-box" type="radio" name="board-style" defaultChecked/><span>おかし箱</span></label><label><input id="board-wood" type="radio" name="board-style"/><span>木の盤</span></label><label><input id="board-grass" type="radio" name="board-style"/><span>若草</span></label><label><input id="board-ink" type="radio" name="board-style"/><span>墨色</span></label></fieldset>}
function Player({side,p,thinking,players,setPlayers}:{side:Side;p:Position;thinking:boolean;players:Record<Side,'human'|'ai'>;setPlayers:(v:Record<Side,'human'|'ai'>)=>void}){return <div className={`player ${side} ${p.turn===side?'active':''}`}><div className={`avatar ${side}`}>{side==='sente'?'先':'後'}</div><div className="info"><b>{side==='sente'?'先手':'後手'}</b><span>{p.turn===side?(thinking?'● かんがえ中…':'● 手番です'):'待っています'}</span></div><select aria-label={`${side==='sente'?'先手':'後手'}の担当`} value={players[side]} onChange={e=>setPlayers({...players,[side]:e.target.value as 'human'|'ai'})}><option value="human">👤 人間</option><option value="ai">🤖 AI</option></select></div>}
function PieceIcon({kind,pieceSet,pieceRoot}:{kind:Kind;pieceSet:PieceSet;pieceRoot:string}){const samuraiFile=kind==='lion'?'lion-mounted-sword':kind;const src=pieceRoot.endsWith('/samurai')?`${pieceRoot}/${samuraiFile}.png?v=3`:`${pieceRoot}/${pieceSet}/${kind}.png?v=7`;return <img className="piece-icon sweet-icon" src={src} alt="" draggable={false}/>}
function MovementGuides({kind,side}:{kind:Kind;side:Side}){return <span className="movement-guides" aria-hidden="true">{vec(kind,side).map(([dr,dc])=><i key={`${dr},${dc}`} style={{gridRow:dr+2,gridColumn:dc+2,alignSelf:dr<0?'start':dr>0?'end':'center',justifySelf:dc<0?'start':dc>0?'end':'center'}}/>)}</span>}
function Hand({side,p,sel,setSel,players,pieceSet,names,pieceRoot}:{side:Side;p:Position;sel:{from?:number;hand?:number}|null;setSel:(v:{hand:number})=>void;players:Record<Side,'human'|'ai'>;pieceSet:PieceSet;names:Record<Kind,string>;pieceRoot:string}){return <div className={`hand ${side}`}><span>もちごま</span><div>{p.hands[side].length?p.hands[side].map((k,i)=><button aria-label={names[k]} disabled={p.turn!==side||players[side]==='ai'} onClick={()=>setSel({hand:i})} className={sel?.hand===i&&sel.from===undefined?'selected':''} key={i}><PieceIcon kind={k} pieceSet={pieceSet} pieceRoot={pieceRoot}/></button>):<em>なし</em>}</div></div>}
export default App
